blueprint:
  name: Heating Control - Window/Door Open Detection
  source_url: https://raw.githubusercontent.com/jcspenle/HA_SensorPilotWire/main/blueprints/automation/jcspenle/heating_window_door_control.yaml
  description: >
    Automated heating control with window/door sensors.
    - Up to 6 sensors per room (separate lists for windows and doors).
    - Windows: immediate action; Doors: action after 4 minutes open.
    - Configurable modes when open/closed (comfort, comfort-1, comfort-2, eco, off).
  domain: automation

  input:
    climate_entity:
      name: Climate Entity (Heater)
      selector:
        entity:
          domain: climate

    window_sensors:
      name: Window Sensors
      selector:
        entity:
          domain: binary_sensor
          device_class: window
          multiple: true

    door_sensors:
      name: Door Sensors
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: true

    mode_when_open:
      name: Mode When Open
      selector:
        select:
          options: [comfort, comfort-1, comfort-2, eco, off]
      default: off

    mode_when_closed:
      name: Mode When Closed
      selector:
        select:
          options: [comfort, comfort-1, comfort-2, eco, off]
      default: comfort

# Variables
variables:
  climate: !input climate_entity
  open_mode: !input mode_when_open
  closed_mode: !input mode_when_closed
  windows: !input window_sensors
  doors: !input door_sensors
  all_sensors: >
    {{ (windows | default([])) + (doors | default([])) }}

trigger:
  # Window opened -> immediate
  - platform: state
    entity_id: !input window_sensors
    to: 'on'
    id: window_opened

  # Door opened -> after 4 minutes
  - platform: state
    entity_id: !input door_sensors
    to: 'on'
    for: '00:04:00'
    id: door_opened

  # Any sensor closed
  - platform: state
    entity_id: !input window_sensors
    to: 'off'
    id: sensor_closed
  - platform: state
    entity_id: !input door_sensors
    to: 'off'
    id: sensor_closed

condition:
  # Open triggers always pass; on close triggers, ensure ALL sensors are closed
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.id in ['window_opened','door_opened'] }}"
      - condition: template
        value_template: >
          {{ trigger.id == 'sensor_closed'
             and (expand(all_sensors) | selectattr('state','eq','on') | list | length == 0) }}

action:
  - choose:
      # == OPEN CASE ==
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['window_opened','door_opened'] }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ open_mode == 'off' }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity
            default:
              - service: climate.set_preset_mode
                target:
                  entity_id: !input climate_entity
                data:
                  preset_mode: "{{ open_mode }}"

      # == ALL CLOSED CASE ==
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'sensor_closed' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ closed_mode == 'off' }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity
            default:
              - service: climate.turn_on
                target:
                  entity_id: !input climate_entity
              - service: climate.set_preset_mode
                target:
                  entity_id: !input climate_entity
                data:
                  preset_mode: "{{ closed_mode }}"
    default: []
mode: single

