blueprint:
  name: Heating Control - Window/Door Open Detection
  source_url: https://raw.githubusercontent.com/jcspenle/HA_SensorPilotWire/main/blueprints/automation/jcspenle/heating_window_door_control.yaml
  description: >
    Automated heating control with window/door sensors.
    - Windows: immediate action; Doors: action after a configurable delay (default 4 minutes).
    - Configurable modes when open/closed (comfort, comfort-1, comfort-2, eco, off).
    - Automation status selector (Activated / Bypass) + helper bypass switch.
    - Window sensors required; door sensors optional.
  domain: automation

  input:
    automation_status:
      name: Automation status
      description: Choose 'Activated' to enable logic or 'Bypass' to disable it.
      selector:
        select:
          options: ["Activated","Bypass"]
      default: "Activated"

    bypass_switch:
      name: Bypass switch (input_boolean)
      description: When ON, disables this automation (maintenance / battery issue / manual override).
      selector:
        entity:
          domain: input_boolean

    climate_entity:
      name: Climate Entity (Heater)
      selector:
        entity:
          domain: climate

    window_sensors:
      name: Window Sensors (required)
      description: Select one or more window sensors for this room.
      selector:
        entity:
          domain: binary_sensor
          device_class: window
          multiple: true

    door_sensors:
      name: Door Sensors (optional)
      description: Select door sensors for this room (delay before action applies). Leave empty if none.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: true
      default: []

    door_open_delay:
      name: Door open delay
      description: Minimum continuous open time before action for DOOR sensors.
      selector:
        duration: {}
      default: "00:04:00"

    mode_when_open:
      name: Mode When Open
      description: Climate preset when any window is open (immediate) or any door is open for the delay.
      selector:
        select:
          options: ["comfort","comfort-1","comfort-2","eco","off"]
      default: "off"

    mode_when_closed:
      name: Mode When Closed
      description: Climate preset when ALL sensors are closed (restore mode).
      selector:
        select:
          options: ["comfort","comfort-1","comfort-2","eco","off"]
      default: "comfort"

# ===== Variables =====
variables:
  status: !input automation_status
  bypass: !input bypass_switch
  climate: !input climate_entity
  open_mode: !input mode_when_open
  closed_mode: !input mode_when_closed
  windows: !input window_sensors
  doors: !input door_sensors
  door_delay: !input door_open_delay
  all_sensors: >
    {{ (windows | default([])) + (doors | default([])) }}

# ===== Triggers =====
trigger:
  # Any window opened (immediate)
  - platform: state
    entity_id: !input window_sensors
    to: "on"
    id: opened

  # Any door opened (no 'for' here; delay handled in actions; list may be empty)
  - platform: state
    entity_id: !input door_sensors
    to: "on"
    id: opened

  # Any sensor closed
  - platform: state
    entity_id: !input window_sensors
    to: "off"
    id: closed
  - platform: state
    entity_id: !input door_sensors
    to: "off"
    id: closed

# ===== Conditions =====
condition:
  # Must be activated via status
  - condition: template
    value_template: "{{ status == 'Activated' }}"
  # Bypass helper must be OFF
  - condition: template
    value_template: "{{ is_state(bypass, 'off') }}"
  # Require at least one window sensor selected
  - condition: template
    value_template: "{{ (windows | default([])) | length > 0 }}"
  # If open-trigger -> always proceed; on close-trigger -> ensure ALL sensors are closed
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.id == 'opened' }}"
      - condition: template
        value_template: >
          {{ trigger.id == 'closed'
             and (expand(all_sensors) | selectattr('state','eq','on') | list | length == 0) }}

# ===== Actions =====
action:
  - choose:
      # === OPEN CASE ===
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'opened' }}"
        sequence:
          # If it's a DOOR (in the 'doors' list), wait the configured delay and ensure still open
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.entity_id in doors }}"
                sequence:
                  - delay: !input door_open_delay
                  - condition: template
                    value_template: "{{ is_state(trigger.entity_id, 'on') }}"
            default: []
          # Apply OPEN mode
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ open_mode == 'off' }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity
            default:
              - service: climate.set_preset_mode
                target:
                  entity_id: !input climate_entity
                data:
                  preset_mode: "{{ open_mode }}"

      # === ALL CLOSED CASE ===
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'closed' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ closed_mode == 'off' }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity
            default:
              - service: climate.turn_on
                target:
                  entity_id: !input climate_entity
              - service: climate.set_preset_mode
                target:
                  entity_id: !input climate_entity
                data:
                  preset_mode: "{{ closed_mode }}"
    default: []

mode: single
