blueprint:
  name: Heating Control - Window/Door Open Detection v1.0.2
  source_url: https://raw.githubusercontent.com/jcspenle/HA_SensorPilotWire/main/blueprints/automation/jcspenle/heating_window_door_control.yaml
  description: >
    Automated heating control with window/door sensors.
    - Windows: immediate action; Doors: action after a configurable delay (default 4 minutes).
    - Configurable modes when open/closed (comfort, comfort-1, comfort-2, eco, off).
    - Automation status selector (Activated / Bypass).
    - Window sensors required; door sensors optional.
    - Support for inverted sensor logic (on=closed / off=open).
  domain: automation

  input:
    automation_status:
      name: Automation status
      description: Choose 'Activated' to enable logic or 'Bypass' to disable it.
      selector:
        select:
          options: ["Activated","Bypass"]
      default: "Activated"

    climate_entity:
      name: Climate Entity (Heater)
      selector:
        entity:
          domain: climate

    window_sensors:
      name: Window Sensors (required)
      description: Select one or more window sensors for this room.
      selector:
        entity:
          domain: binary_sensor
          device_class: window
          multiple: true

    door_sensors:
      name: Door Sensors (optional)
      description: Select door sensors for this room (delay before action applies). Leave empty if none.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: true
      default: []

    sensor_logic:
      name: Sensor Logic
      description: "Normal: on=open, off=closed | Inverted: on=closed, off=open"
      selector:
        select:
          options: ["Normal","Inverted"]
      default: "Normal"

    door_open_delay:
      name: Door open delay
      description: Minimum continuous open time before action for DOOR sensors.
      selector:
        duration: {}
      default:
        hours: 0
        minutes: 4
        seconds: 0

    mode_when_open:
      name: Mode When Open
      description: Climate preset when any window is open (immediate) or any door is open for the delay.
      selector:
        select:
          options: ["comfort","comfort-1","comfort-2","eco","off"]
      default: "off"

    mode_when_closed:
      name: Mode When Closed
      description: Climate preset when ALL sensors are closed (restore mode).
      selector:
        select:
          options: ["comfort","comfort-1","comfort-2","eco","off"]
      default: "comfort"

# ===== Variables =====
variables:
  status: !input automation_status
  climate: !input climate_entity
  open_mode: !input mode_when_open
  closed_mode: !input mode_when_closed
  windows: !input window_sensors
  doors: !input door_sensors
  door_delay: !input door_open_delay
  logic: !input sensor_logic
  all_sensors: >
    {{ (windows | default([])) + (doors | default([])) }}
  has_doors: >
    {{ (doors | default([]) | length) > 0 }}
  # Define open/closed states based on sensor logic
  state_open: >
    {{ 'off' if logic == 'Inverted' else 'on' }}
  state_closed: >
    {{ 'on' if logic == 'Inverted' else 'off' }}

# ===== Triggers =====
trigger:
  # Windows state change
  - platform: state
    entity_id: !input window_sensors
    id: window_state_change

  # Template trigger for doors opened (only fires if doors exist)
  - platform: template
    value_template: >
      {% set door_list = doors | default([]) %}
      {% set open_state = 'off' if logic == 'Inverted' else 'on' %}
      {{ door_list | length > 0 and 
         expand(door_list) | selectattr('state','eq', open_state) | list | length > 0 }}
    id: door_opened

  # Template trigger for door closed (only fires if doors exist)
  - platform: template
    value_template: >
      {% set door_list = doors | default([]) %}
      {% set closed_state = 'on' if logic == 'Inverted' else 'off' %}
      {{ door_list | length > 0 and 
         expand(door_list) | selectattr('state','eq', closed_state) | list | length > 0 }}
    id: door_closed

# ===== Conditions =====
condition:
  # Must be activated via status
  - condition: template
    value_template: "{{ status == 'Activated' }}"
  # Require at least one window sensor selected
  - condition: template
    value_template: "{{ (windows | default([])) | length > 0 }}"

# ===== Actions =====
action:
  - choose:
      # === WINDOW STATE CHANGE ===
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'window_state_change' }}"
        sequence:
          - choose:
              # WINDOW OPENED (immediate action)
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.to_state.state == state_open }}"
                sequence:
                  # Apply OPEN mode immediately
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ open_mode == 'off' }}"
                        sequence:
                          - service: climate.turn_off
                            target:
                              entity_id: !input climate_entity
                    default:
                      - service: climate.set_preset_mode
                        target:
                          entity_id: !input climate_entity
                        data:
                          preset_mode: "{{ open_mode }}"

              # WINDOW CLOSED - check if ALL sensors are closed
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.to_state.state == state_closed }}"
                  # Verify ALL sensors are now closed
                  - condition: template
                    value_template: >
                      {{ expand(all_sensors) | selectattr('state','eq', state_open) | list | length == 0 }}
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ closed_mode == 'off' }}"
                        sequence:
                          - service: climate.turn_off
                            target:
                              entity_id: !input climate_entity
                    default:
                      - service: climate.turn_on
                        target:
                          entity_id: !input climate_entity
                      - service: climate.set_preset_mode
                        target:
                          entity_id: !input climate_entity
                        data:
                          preset_mode: "{{ closed_mode }}"

      # === DOOR OPENED (with delay) ===
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'door_opened' }}"
        sequence:
          # Wait configured delay
          - delay: !input door_open_delay
          # Verify at least one door is still open
          - condition: template
            value_template: >
              {{ expand(doors) | selectattr('state','eq', state_open) | list | length > 0 }}
          # Apply OPEN mode
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ open_mode == 'off' }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity
            default:
              - service: climate.set_preset_mode
                target:
                  entity_id: !input climate_entity
                data:
                  preset_mode: "{{ open_mode }}"

      # === DOOR CLOSED ===
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'door_closed' }}"
          # Verify ALL sensors are now closed
          - condition: template
            value_template: >
              {{ expand(all_sensors) | selectattr('state','eq', state_open) | list | length == 0 }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ closed_mode == 'off' }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity
            default:
              - service: climate.turn_on
                target:
                  entity_id: !input climate_entity
              - service: climate.set_preset_mode
                target:
                  entity_id: !input climate_entity
                data:
                  preset_mode: "{{ closed_mode }}"
    default: []

mode: single
