blueprint:
  name: Heating Control - Window/Door Open Detection v2.0
  source_url: https://raw.githubusercontent.com/jcspenle/HA_SensorPilotWire/main/blueprints/automation/jcspenle/heating_window_door_control.yaml
  description: >
    Automated heating control with window/door sensors.
    - Windows: immediate action; Doors: action after a configurable delay (default 4 minutes).
    - Configurable modes when open/closed (comfort, comfort-1, comfort-2, eco, off).
    - Automation status selector (Activated / Bypass).
    - Window sensors required; door sensors optional.
    - Support for inverted sensor logic (on=closed / off=open).
    - Notifications in French when heating state changes.
    - Activity logging with room names.
    - Smart mode: restores previous preset when closing.
    - Dashboard sensors for windows and doors status.
  domain: automation

  input:
    automation_status:
      name: Statut de l'automation
      description: Choisir 'Activé' pour activer la logique ou 'Bypass' pour la désactiver.
      selector:
        select:
          options: ["Activé","Bypass"]
      default: "Activé"

    climate_entity:
      name: Entité Climate (Radiateur)
      selector:
        entity:
          domain: climate

    window_sensors:
      name: Capteurs de fenêtres (requis)
      description: Sélectionner un ou plusieurs capteurs de fenêtre pour cette pièce.
      selector:
        entity:
          domain: binary_sensor
          device_class: window
          multiple: true

    door_sensors:
      name: Capteurs de portes (optionnel)
      description: Sélectionner les capteurs de porte pour cette pièce (délai avant action). Laisser vide si aucun.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: true
      default: []

    sensor_logic:
      name: Logique des capteurs
      description: "Normal: on=ouvert, off=fermé | Inversé: on=fermé, off=ouvert"
      selector:
        select:
          options: ["Normal","Inversé"]
      default: "Normal"

    door_open_delay:
      name: Délai d'ouverture porte
      description: Temps minimum d'ouverture continue avant action pour les capteurs de PORTE.
      selector:
        duration: {}
      default:
        hours: 0
        minutes: 4
        seconds: 0

    min_closed_duration:
      name: Durée minimale de fermeture
      description: Attendre ce délai avant de restaurer le chauffage (évite les changements rapides).
      selector:
        duration: {}
      default:
        hours: 0
        minutes: 2
        seconds: 0

    mode_when_open:
      name: Mode quand ouvert
      description: Preset du climate quand une fenêtre est ouverte (immédiat) ou une porte est ouverte (après délai).
      selector:
        select:
          options: ["comfort","comfort-1","comfort-2","eco","off"]
      default: "off"

    mode_when_closed:
      name: Mode quand fermé
      description: Preset du climate quand TOUS les capteurs sont fermés (mode de restauration).
      selector:
        select:
          options: ["comfort","comfort-1","comfort-2","eco","off"]
      default: "comfort"

    smart_restore:
      name: Restauration intelligente
      description: Mémoriser et restaurer le mode précédent au lieu d'utiliser le mode par défaut.
      selector:
        boolean: {}
      default: false

    room_name:
      name: Nom de la pièce
      description: Nom de la pièce pour les notifications et logs (ex. "Salon", "Chambre").
      selector:
        text: {}
      default: "Pièce"

    notify_service:
      name: Service de notification (optionnel)
      description: Service notify à utiliser (ex. "notify.mobile_app_iphone", "notify.all_devices"). Laisser vide pour désactiver.
      selector:
        text: {}
      default: ""

    log_entity:
      name: Entité de log (optionnel)
      description: input_text pour logger l'activité (créer un helper input_text si besoin). Laisser vide pour désactiver.
      selector:
        entity:
          domain: input_text
      default: ""

    window_status_sensor:
      name: Capteur d'état fenêtres (optionnel)
      description: input_text pour afficher l'état des fenêtres dans le dashboard. Laisser vide pour désactiver.
      selector:
        entity:
          domain: input_text
      default: ""

    door_status_sensor:
      name: Capteur d'état portes (optionnel)
      description: input_text pour afficher l'état des portes dans le dashboard. Laisser vide pour désactiver.
      selector:
        entity:
          domain: input_text
      default: ""

# ===== Variables =====
variables:
  status: !input automation_status
  climate: !input climate_entity
  open_mode: !input mode_when_open
  closed_mode: !input mode_when_closed
  windows: !input window_sensors
  doors: !input door_sensors
  door_delay: !input door_open_delay
  min_close_delay: !input min_closed_duration
  logic: !input sensor_logic
  smart_mode: !input smart_restore
  room: !input room_name
  notify_svc: !input notify_service
  log_ent: !input log_entity
  window_sensor: !input window_status_sensor
  door_sensor: !input door_status_sensor
  all_sensors: >
    {{ (windows | default([])) + (doors | default([])) }}
  has_doors: >
    {{ (doors | default([]) | length) > 0 }}
  state_open: >
    {{ 'off' if logic == 'Inversé' else 'on' }}
  state_closed: >
    {{ 'on' if logic == 'Inversé' else 'off' }}
  current_preset: >
    {{ state_attr(climate, 'preset_mode') }}

# ===== Triggers =====
trigger:
  # Windows state change
  - platform: state
    entity_id: !input window_sensors
    id: window_state_change

  # Template trigger for doors opened (only fires if doors exist)
  - platform: template
    value_template: >
      {% set door_list = doors | default([]) %}
      {% set open_state = 'off' if logic == 'Inversé' else 'on' %}
      {{ door_list | length > 0 and 
         expand(door_list) | selectattr('state','eq', open_state) | list | length > 0 }}
    id: door_opened

  # Template trigger for door closed (only fires if doors exist)
  - platform: template
    value_template: >
      {% set door_list = doors | default([]) %}
      {% set closed_state = 'on' if logic == 'Inversé' else 'off' %}
      {{ door_list | length > 0 and 
         expand(door_list) | selectattr('state','eq', closed_state) | list | length > 0 }}
    id: door_closed

# ===== Conditions =====
condition:
  # Must be activated via status
  - condition: template
    value_template: "{{ status == 'Activé' }}"
  # Require at least one window sensor selected
  - condition: template
    value_template: "{{ (windows | default([])) | length > 0 }}"

# ===== Actions =====
action:
  - choose:
      # === WINDOW STATE CHANGE ===
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'window_state_change' }}"
        sequence:
          - choose:
              # WINDOW OPENED (immediate action)
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.to_state.state == state_open }}"
                sequence:
                  # Update window status sensor
                  - if:
                      - condition: template
                        value_template: "{{ window_sensor != '' }}"
                    then:
                      - service: input_text.set_value
                        target:
                          entity_id: "{{ window_sensor }}"
                        data:
                          value: >
                            {{ expand(windows) | selectattr('state','eq', state_open) | list | length }} fenêtre(s) ouverte(s)
                  
                  # Apply OPEN mode immediately
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ open_mode == 'off' }}"
                        sequence:
                          - service: climate.turn_off
                            target:
                              entity_id: !input climate_entity
                    default:
                      - service: climate.set_preset_mode
                        target:
                          entity_id: !input climate_entity
                        data:
                          preset_mode: "{{ open_mode }}"
                  
                  # Log action
                  - if:
                      - condition: template
                        value_template: "{{ log_ent != '' }}"
                    then:
                      - service: input_text.set_value
                        target:
                          entity_id: "{{ log_ent }}"
                        data:
                          value: >
                            {{ now().strftime('%H:%M') }} - {{ room }}: Fenêtre ouverte - Chauffage {{ 'ÉTEINT' if open_mode == 'off' else 'mode ' + open_mode }}
                  
                  # Send notification
                  - if:
                      - condition: template
                        value_template: "{{ notify_svc != '' }}"
                    then:
                      - service: "{{ notify_svc }}"
                        data:
                          message: >
                            🪟 {{ room }}: Fenêtre ouverte - Chauffage {{ 'éteint' if open_mode == 'off' else 'réduit (' + open_mode + ')' }}
                          title: "Chauffage désactivé"

              # WINDOW CLOSED - check if ALL sensors are closed
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.to_state.state == state_closed }}"
                sequence:
                  # Wait minimum closed duration (anti-bounce)
                  - delay: !input min_closed_duration
                  # Verify ALL sensors are now closed
                  - condition: template
                    value_template: >
                      {{ expand(all_sensors) | selectattr('state','eq', state_open) | list | length == 0 }}
                  
                  # Update window status sensor
                  - if:
                      - condition: template
                        value_template: "{{ window_sensor != '' }}"
                    then:
                      - service: input_text.set_value
                        target:
                          entity_id: "{{ window_sensor }}"
                        data:
                          value: "Toutes les fenêtres fermées"
                  
                  # Determine mode to restore
                  - variables:
                      restore_mode: >
                        {% if smart_mode and current_preset != none %}
                          {{ current_preset }}
                        {% else %}
                          {{ closed_mode }}
                        {% endif %}
                  
                  # Apply restore mode
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ restore_mode == 'off' }}"
                        sequence:
                          - service: climate.turn_off
                            target:
                              entity_id: !input climate_entity
                    default:
                      - service: climate.turn_on
                        target:
                          entity_id: !input climate_entity
                      - service: climate.set_preset_mode
                        target:
                          entity_id: !input climate_entity
                        data:
                          preset_mode: "{{ restore_mode }}"
                  
                  # Log action
                  - if:
                      - condition: template
                        value_template: "{{ log_ent != '' }}"
                    then:
                      - service: input_text.set_value
                        target:
                          entity_id: "{{ log_ent }}"
                        data:
                          value: >
                            {{ now().strftime('%H:%M') }} - {{ room }}: Tout fermé - Chauffage {{ 'ALLUMÉ' if restore_mode != 'off' else 'ÉTEINT' }} ({{ restore_mode }})
                  
                  # Send notification
                  - if:
                      - condition: template
                        value_template: "{{ notify_svc != '' }}"
                    then:
                      - service: "{{ notify_svc }}"
                        data:
                          message: >
                            ✅ {{ room }}: Tout fermé - Chauffage {{ 'rallumé' if restore_mode != 'off' else 'éteint' }} ({{ restore_mode }})
                          title: "Chauffage restauré"

      # === DOOR OPENED (with delay) ===
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'door_opened' }}"
        sequence:
          # Wait configured delay
          - delay: !input door_open_delay
          # Verify at least one door is still open
          - condition: template
            value_template: >
              {{ expand(doors) | selectattr('state','eq', state_open) | list | length > 0 }}
          
          # Update door status sensor
          - if:
              - condition: template
                value_template: "{{ door_sensor != '' }}"
            then:
              - service: input_text.set_value
                target:
                  entity_id: "{{ door_sensor }}"
                data:
                  value: >
                    {{ expand(doors) | selectattr('state','eq', state_open) | list | length }} porte(s) ouverte(s)
          
          # Apply OPEN mode
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ open_mode == 'off' }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity
            default:
              - service: climate.set_preset_mode
                target:
                  entity_id: !input climate_entity
                data:
                  preset_mode: "{{ open_mode }}"
          
          # Log action
          - if:
              - condition: template
                value_template: "{{ log_ent != '' }}"
            then:
              - service: input_text.set_value
                target:
                  entity_id: "{{ log_ent }}"
                data:
                  value: >
                    {{ now().strftime('%H:%M') }} - {{ room }}: Porte ouverte (>{{ (door_delay.minutes | default(4)) }}min) - Chauffage {{ 'ÉTEINT' if open_mode == 'off' else 'mode ' + open_mode }}
          
          # Send notification
          - if:
              - condition: template
                value_template: "{{ notify_svc != '' }}"
            then:
              - service: "{{ notify_svc }}"
                data:
                  message: >
                    🚪 {{ room }}: Porte ouverte - Chauffage {{ 'éteint' if open_mode == 'off' else 'réduit (' + open_mode + ')' }}
                  title: "Chauffage désactivé"

      # === DOOR CLOSED ===
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'door_closed' }}"
        sequence:
          # Wait minimum closed duration
          - delay: !input min_closed_duration
          # Verify ALL sensors are now closed
          - condition: template
            value_template: >
              {{ expand(all_sensors) | selectattr('state','eq', state_open) | list | length == 0 }}
          
          # Update door status sensor
          - if:
              - condition: template
                value_template: "{{ door_sensor != '' }}"
            then:
              - service: input_text.set_value
                target:
                  entity_id: "{{ door_sensor }}"
                data:
                  value: "Toutes les portes fermées"
          
          # Determine mode to restore
          - variables:
              restore_mode: >
                {% if smart_mode and current_preset != none %}
                  {{ current_preset }}
                {% else %}
                  {{ closed_mode }}
                {% endif %}
          
          # Apply restore mode
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ restore_mode == 'off' }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity
            default:
              - service: climate.turn_on
                target:
                  entity_id: !input climate_entity
              - service: climate.set_preset_mode
                target:
                  entity_id: !input climate_entity
                data:
                  preset_mode: "{{ restore_mode }}"
          
          # Log action
          - if:
              - condition: template
                value_template: "{{ log_ent != '' }}"
            then:
              - service: input_text.set_value
                target:
                  entity_id: "{{ log_ent }}"
                data:
                  value: >
                    {{ now().strftime('%H:%M') }} - {{ room }}: Tout fermé - Chauffage {{ 'ALLUMÉ' if restore_mode != 'off' else 'ÉTEINT' }} ({{ restore_mode }})
          
          # Send notification
          - if:
              - condition: template
                value_template: "{{ notify_svc != '' }}"
            then:
              - service: "{{ notify_svc }}"
                data:
                  message: >
                    ✅ {{ room }}: Tout fermé - Chauffage {{ 'rallumé' if restore_mode != 'off' else 'éteint' }} ({{ restore_mode }})
                  title: "Chauffage restauré"
    default: []

mode: single
